import 'package:get/get.dart';

class Localstring extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          "Crisis Dashboard": "Crisis Dashboard",
          "Urgent Crises": "Urgent Crises",
          "Predicted Crises": "Predicted Crises",
          "Natural Disaster": "Natural Disaster",
          "Humanitarian Conflict": "Humanitarian Conflict",
          "Pandemic": "Pandemic",
          "Failed to load crisis updates.": "Failed to load crisis updates.",
          "Try Again": "Try Again",
          "No Title": "No Title",
          "No Description Available": "No Description Available",
          "Unknown Location": "Unknown Location",
          "Unknown": "Unknown",
          "Volunteering Campaigns": "Volunteering Campaigns",
          "You Volunteered in": "You Volunteered in",
          "View": "View",
          "Featured Campaigns": "Featured Campaigns",
          "Donate": "Donate",
          "Make a Difference": "Make a Difference",
          "Your support can save lives and provide essential aid.":
              "Your support can save lives and provide essential aid.",
          "All Causes": "All Causes",
          "All": "All",
          "Disaster Relief": "Disaster Relief",
          "Medical Aid": "Medical Aid",
          "Food & Water": "Food & Water",
          "Cause 1": "Cause 1",
          "Organization name": "Organization name",
          "Login Required": "Login Required",
          "You need to login to donate. Please login first.":
              "You need to login to donate. Please login first.",
          "Cancel": "Cancel",
          "Login": "Login",
          "Learn & Share": "Learn & Share",
          "Education & Awareness": "Education & Awareness",
          "Learn about humanitarian crises and share knowledge":
              "Learn about humanitarian crises and share knowledge",
          "Featured Content": "Featured Content",
          "Educational Resources": "Educational Resources",
          "Active Campaigns": "Active Campaigns",
          "#StandWithRefugees": "#StandWithRefugees",
          "Share your support for refugees using the hashtag #StandWithRefugees on social media.":
              "Share your support for refugees using the hashtag #StandWithRefugees on social media.",
          "#ClimateAction": "#ClimateAction",
          "Join the campaign to raise awareness about climate-related disasters.":
              "Join the campaign to raise awareness about climate-related disasters.",
          "DOCUMENTARY": "DOCUMENTARY",
          "Understanding Climate Disasters: Causes and Responses":
              "Understanding Climate Disasters: Causes and Responses",
          "Learn how climate change affects disaster frequency and how humanitarian organizations respond.":
              "Learn how climate change affects disaster frequency and how humanitarian organizations respond.",
          "Watch": "Watch",
          "How Humanitarian Aid Works": "How Humanitarian Aid Works",
          "Refugee Crisis Explained": "Refugee Crisis Explained",
          "Understanding Disaster Response": "Understanding Disaster Response",
          "The Role of NGOs in Crisis Situations":
              "The Role of NGOs in Crisis Situations",
          "Climate Change and Humanitarian Crises":
              "Climate Change and Humanitarian Crises",
          "Article": "Article",
          "Video": "Video",
          "Infographic": "Infographic",
          "Podcast": "Podcast",
          "Interactive": "Interactive",
          "Share": "Share",
          "Learn More": "Learn More",
          "My Profile": "My Profile",
          "Your Impact": "Your Impact",
          "Total Donated": "Total Donated",
          "Donations": "Donations",
          "Organizations": "Organizations",
          "View Detailed Impact": "View Detailed Impact",
          "Log Out?": "Log Out?",
          "You will be signed out of the application. Do you really want to log out?":
              "You will be signed out of the application. Do you really want to log out?",
          "No": "No",
          "Yes": "Yes",
          "Logout": "Logout",
          "Login/Signup": "Login/Signup",
          "Sign Up/ Login to view details": "Sign Up/ Login to view details",
          "Community Discussion": "Community Discussion",
          "Create a Post": "Create a Post",
          "Title": "Title",
          "Description": "Description",
          "Post": "Post",
          "Comments": "Comments",
          "Add Comment": "Add Comment",
          "Comment": "Comment",
          "You need to login to comment/post. Please login first.":
              "You need to login to comment/post. Please login first.",
          "Likes": "Likes",
          "Profile": "Profile",
          "Awareness": "Awareness",
          "Volunteer": "Volunteer",
          "Dashboard": "Dashboard"
        },
        "hi_IN": {
          "Crisis Dashboard": "संकट डैशबोर्ड",
          "Urgent Crises": "तत्काल संकट",
          "Predicted Crises": "अनुमानित संकट",
          "Natural Disaster": "प्राकृतिक आपदा",
          "Humanitarian Conflict": "मानवीय संघर्ष",
          "Pandemic": "महामारी",
          "Failed to load crisis updates.": "संकट अपडेट लोड करने में विफल।",
          "Try Again": "फिर से प्रयास करें",
          "No Title": "कोई शीर्षक नहीं",
          "No Description Available": "कोई विवरण उपलब्ध नहीं",
          "Unknown Location": "अज्ञात स्थान",
          "Unknown": "अज्ञात",
          "Volunteering Campaigns": "स्वयंसेवी अभियानों",
          "You Volunteered in": "आपने इसमें स्वयंसेवा की",
          "View": "देखें",
          "Featured Campaigns": "विशेष अभियान",
          "Donate": "दान करें",
          "Make a Difference": "परिवर्तन लाएँ",
          "Your support can save lives and provide essential aid.":
              "आपका समर्थन जीवन बचा सकता है और आवश्यक सहायता प्रदान कर सकता है।",
          "All Causes": "सभी कारण",
          "All": "सभी",
          "Disaster Relief": "आपदा राहत",
          "Medical Aid": "चिकित्सा सहायता",
          "Food & Water": "भोजन और पानी",
          "Cause 1": "कारण 1",
          "Organization name": "संगठन का नाम",
          "Login Required": "लॉगिन आवश्यक",
          "You need to login to donate. Please login first.":
              "दान करने के लिए आपको लॉगिन करना होगा। कृपया पहले लॉगिन करें।",
          "Cancel": "रद्द करें",
          "Login": "लॉगिन",
          "Learn & Share": "सीखें और साझा करें",
          "Education & Awareness": "शिक्षा और जागरूकता",
          "Learn about humanitarian crises and share knowledge":
              "मानवीय संकटों के बारे में जानें और ज्ञान साझा करें",
          "Featured Content": "विशेष सामग्री",
          "Educational Resources": "शैक्षिक संसाधन",
          "Active Campaigns": "सक्रिय अभियान",
          "#StandWithRefugees": "#शरणार्थियोंकेसाथखड़ेहों",
          "Share your support for refugees using the hashtag #StandWithRefugees on social media.":
              "सोशल मीडिया पर हैशटैग #शरणार्थियोंकेसाथखड़ेहों का उपयोग करके शरणार्थियों के लिए अपना समर्थन साझा करें।",
          "#ClimateAction": "#जलवायुप्रभाव",
          "Join the campaign to raise awareness about climate-related disasters.":
              "जलवायु से संबंधित आपदाओं के बारे में जागरूकता बढ़ाने के लिए अभियान में शामिल हों।",
          "DOCUMENTARY": "डॉक्यूमेंट्री",
          "Understanding Climate Disasters: Causes and Responses":
              "जलवायु आपदाओं को समझना: कारण और प्रतिक्रियाएँ",
          "Learn how climate change affects disaster frequency and how humanitarian organizations respond.":
              "जानें कि जलवायु परिवर्तन आपदा की आवृत्ति को कैसे प्रभावित करता है और मानवीय संगठन कैसे प्रतिक्रिया देते हैं।",
          "Watch": "देखें",
          "Logout": "लॉगआउट",
          "Likes": "पसंद",
          "Profile": "प्रोफ़ाइल",
          "Awareness": "जागरूकता",
          "Volunteer": "स्वयंसेवक",
          "Dashboard": "डैशबोर्ड",
          "Sign Up/ Login to view details": "विवरण देखने के लिए साइन अप / लॉगिन करें",
          "Community Discussion": "सामुदायिक चर्चा",
          "Create a Post": "एक पोस्ट बनाएँ",
          "Title": "शीर्षक",
          "Description": "विवरण",
          "Cancel": "रद्द करें",
          "Post": "पोस्ट करें",
          "Comments": "टिप्पणियाँ",
          "Likes": "पसंद",
          "Add Comment": "टिप्पणी जोड़ें",
          "Comment": "टिप्पणी",
          "Login Required": "लॉगिन आवश्यक",
          "You need to login to comment/post. Please login first.": "टिप्पणी/पोस्ट करने के लिए आपको लॉगिन करना होगा। कृपया पहले लॉगिन करें।",
          "Login": "लॉगिन",
          "My Profile": "मेरी प्रोफ़ाइल",
          "Login/Signup": "लॉगिन/साइनअप",
          "Your Impact": "आपका प्रभाव",
          "Error loading donations": "दान लोड करने में त्रुटि",
          "Total Donated": "कुल दान",
          "Donations": "दान",
          "Organizations": "संगठन",
          "View Detailed Impact": "विस्तृत प्रभाव देखें",
          "Log Out?": "लॉग आउट करें?",
          "You will be signed out of the application. Do you really want to log out?": "आप एप्लिकेशन से लॉग आउट हो जाएंगे। क्या आप वाकई लॉग आउट करना चाहते हैं?",
          "No": "नहीं",
          "Yes": "हाँ",
          "Logout": "लॉगआउट"
        },
        "mr_IN": {
          "Crisis Dashboard": "संकट डॅशबोर्ड",
          "Urgent Crises": "तातडीची संकटे",
          "Predicted Crises": "भाकीत संकटे",
          "Natural Disaster": "नैसर्गिक आपत्ती",
          "Humanitarian Conflict": "मानवी संघर्ष",
          "Pandemic": "महासाथ",
          "Failed to load crisis updates.": "संकट अद्यतन लोड करण्यात अयशस्वी.",
          "Try Again": "पुन्हा प्रयत्न करा",
          "No Title": "शीर्षक नाही",
          "No Description Available": "वर्णन उपलब्ध नाही",
          "Unknown Location": "अज्ञात स्थान",
          "Unknown": "अज्ञात",
          "Volunteering Campaigns": "स्वयंसेवी मोहिमा",
          "You Volunteered in": "तुम्ही स्वयंसेवा केली",
          "View": "पहा",
          "Featured Campaigns": "वैशिष्ट्यीकृत मोहिमा",
          "Donate": "दान करा",
          "Make a Difference": "बदल घडवा",
          "Your support can save lives and provide essential aid.":
              "तुमचा पाठिंबा जीव वाचवू शकतो आणि आवश्यक मदत पुरवू शकतो.",
          "All Causes": "सर्व कारणे",
          "All": "सर्व",
          "Disaster Relief": "आपत्ती मदत",
          "Medical Aid": "वैद्यकीय मदत",
          "Food & Water": "अन्न आणि पाणी",
          "Cause 1": "कारण 1",
          "Organization name": "संस्थेचे नाव",
          "Login Required": "लॉगिन आवश्यक",
          "You need to login to donate. Please login first.":
              "दान करण्यासाठी तुम्हाला लॉगिन करावे लागेल. कृपया प्रथम लॉगिन करा.",
          "Cancel": "रद्द करा",
          "Login": "लॉगिन",
          "Learn & Share": "शिका आणि शेअर करा",
          "Education & Awareness": "शिक्षण आणि जनजागृती",
          "Learn about humanitarian crises and share knowledge":
              "मानवी संकटांबद्दल शिका आणि ज्ञान सामायिक करा",
          "Featured Content": "वैशिष्ट्यीकृत सामग्री",
          "Educational Resources": "शैक्षणिक संसाधने",
          "Active Campaigns": "सक्रिय मोहिमा",
          "#StandWithRefugees": "#शरणार्थ्यांसोबतउभेरहा",
          "Share your support for refugees using the hashtag #StandWithRefugees on social media.":
              "सोशल मीडियावर #शरणार्थ्यांसोबतउभेरहा हॅशटॅग वापरून तुमचा पाठिंबा शेअर करा.",
          "#ClimateAction": "#हवामानक्रिया",
          "Join the campaign to raise awareness about climate-related disasters.":
              "हवामान-संबंधित आपत्तींबद्दल जागरूकता वाढवण्यासाठी मोहिमेत सामील व्हा.",
          "DOCUMENTARY": "दस्तऐवज",
          "Understanding Climate Disasters: Causes and Responses":
              "हवामान आपत्ती समजून घेणे: कारणे आणि प्रतिसाद",
          "Learn how climate change affects disaster frequency and how humanitarian organizations respond.":
              "हवामान बदल आपत्तींच्या वारंवारतेवर कसा परिणाम करतो आणि मानवी संस्था कशा प्रतिसाद देतात ते शिका.",
          "Watch": "पाहा",
          "Logout": "बाहेर पडा",
          "Likes": "आवडले",
          "Profile": "प्रोफाइल",
          "Awareness": "जनजागृती",
          "Volunteer": "स्वयंसेवक",
          "Dashboard": "डॅशबोर्ड",
          "Sign Up/ Login to view details": "तपशील पाहण्यासाठी साइन अप / लॉगिन करा",
          "Community Discussion": "समुदाय चर्चा",
          "Create a Post": "पोस्ट तयार करा",
          "Title": "शिर्षक",
          "Description": "वर्णन",
          "Cancel": "रद्द करा",
          "Post": "पोस्ट करा",
          "Comments": "टिप्पण्या",
          "Likes": "आवडले",
          "Add Comment": "टिप्पणी जोडा",
          "Comment": "टिप्पणी",
          "Login Required": "लॉगिन आवश्यक",
          "You need to login to comment/post. Please login first.": "टिप्पणी/पोस्ट करण्यासाठी तुम्हाला लॉगिन करावे लागेल. कृपया प्रथम लॉगिन करा.",
          "Login": "लॉगिन",
          "My Profile": "माझी प्रोफाइल",
          "Login/Signup": "लॉगिन/साइनअप",
          "Your Impact": "तुमचा प्रभाव",
          "Error loading donations": "दान लोड करताना त्रुटी",
          "Total Donated": "एकूण दान",
          "Donations": "दान",
          "Organizations": "संस्था",
          "View Detailed Impact": "तपशीलवार परिणाम पहा",
          "Log Out?": "लॉग आउट करायचे का?",
          "You will be signed out of the application. Do you really want to log out?": "तुम्ही अॅप्लिकेशनमधून लॉग आउट होणार आहात. तुम्हाला खरोखर लॉग आउट करायचे आहे का?",
          "No": "नाही",
          "Yes": "होय",
          "Logout": "लॉगआउट"
        },
        "ta_IN": {
          "Crisis Dashboard": "அவசர நிலை கண்காணிப்பு பலகம்",
          "Urgent Crises": "அவசரமான நெருக்கடிகள்",
          "Predicted Crises": "முன்கூட்டியே கணிக்கப்பட்ட நெருக்கடிகள்",
          "Natural Disaster": "இயற்கை பேரழிவு",
          "Humanitarian Conflict": "மனிதாபிமான மோதல்",
          "Pandemic": "பரவிய நோய்",
          "Failed to load crisis updates.":
              "நெருக்கடி தகவல்களை ஏற்றுவதில் தோல்வி.",
          "Try Again": "மறுபடியும் முயற்சிக்கவும்",
          "No Title": "தலைப்பு இல்லை",
          "No Description Available": "விளக்கம் இல்லை",
          "Unknown Location": "அறியப்படாத இடம்",
          "Unknown": "அறியப்படாதது",
          "Volunteering Campaigns": "தன்னார்வப் பிரச்சாரங்கள்",
          "You Volunteered in": "நீங்கள் தன்னார்வமாக சேர்ந்த இடம்",
          "View": "காண்க",
          "Featured Campaigns": "சிறப்பு பிரச்சாரங்கள்",
          "Donate": "நன்கொடை",
          "Make a Difference": "மாற்றத்தை ஏற்படுத்துங்கள்",
          "Your support can save lives and provide essential aid.":
              "உங்கள் ஆதரவு உயிர்களை காப்பாற்றி, அத்தியாவசிய உதவிகளை வழங்கலாம்.",
          "All Causes": "அனைத்து காரணங்கள்",
          "All": "அனைத்தும்",
          "Disaster Relief": "அழிவு நிவாரணம்",
          "Medical Aid": "மருத்துவ உதவி",
          "Food & Water": "உணவு & தண்ணீர்",
          "Cause 1": "காரணம் 1",
          "Organization name": "நிறுவனத்தின் பெயர்",
          "Login Required": "உள்நுழைவு அவசியம்",
          "You need to login to donate. Please login first.":
              "நன்கொடை வழங்க உள்நுழைய வேண்டும். தயவுசெய்து முதலில் உள்நுழையவும்.",
          "Cancel": "ரத்து செய்யவும்",
          "Login": "உள்நுழையவும்",
          "Learn & Share": "கற்றுக்கொள்ளுங்கள் & பகிருங்கள்",
          "Education & Awareness": "கல்வி & விழிப்புணர்வு",
          "Learn about humanitarian crises and share knowledge":
              "மனிதாபிமான நெருக்கடிகளைப் பற்றி கற்றுக்கொண்டு அறிவைப் பகிருங்கள்",
          "Featured Content": "சிறப்பு உள்ளடக்கம்",
          "Educational Resources": "கல்வி வளங்கள்",
          "Active Campaigns": "செயலில் உள்ள பிரச்சாரங்கள்",
          "#StandWithRefugees": "#காணியில்லா மக்கள் உடன் நின்றிடுங்கள்",
          "Share your support for refugees using the hashtag #StandWithRefugees on social media.":
              "சமூக ஊடகங்களில் #காணியில்லா மக்கள் உடன் நின்றிடுங்கள் என்ற ஹாஷ்டேக் பயன்படுத்தி உங்கள் ஆதரவை பகிருங்கள்.",
          "#ClimateAction": "#சூழல் நடவடிக்கை",
          "Join the campaign to raise awareness about climate-related disasters.":
              "சூழல் தொடர்பான பேரழிவுகளைப் பற்றிய விழிப்புணர்வை அதிகரிக்க இந்த பிரச்சாரத்தில் சேரவும்.",
          "DOCUMENTARY": "ஆவணப்படம்",
          "Understanding Climate Disasters: Causes and Responses":
              "சூழல் பேரழிவுகளைப் புரிந்துகொள்ளுதல்: காரணங்கள் மற்றும் எதிர்வினைகள்",
          "Learn how climate change affects disaster frequency and how humanitarian organizations respond.":
              "சூழல் மாற்றம் பேரழிவுகளின் அளவை எப்படி பாதிக்கிறது மற்றும் மனிதாபிமான அமைப்புகள் எப்படி பதிலளிக்கின்றன என்பதை அறியவும்.",
          "Watch": "பார்க்கவும்",
          "How Humanitarian Aid Works": "மனிதாபிமான உதவி எவ்வாறு செயல்படுகிறது",
          "Refugee Crisis Explained":
              "காணியில்லா மக்கள் நெருக்கடியின் விளக்கம்",
          "Understanding Disaster Response":
              "பேரழிவு எதிர்வினையைப் புரிந்துகொள்வது",
          "The Role of NGOs in Crisis Situations":
              "நெருக்கடி நிலைகளில் தனியார்துறையின் பங்கு",
          "Climate Change and Humanitarian Crises":
              "சூழல் மாற்றம் மற்றும் மனிதாபிமான நெருக்கடிகள்",
          "Article": "கட்டுரை",
          "Video": "வீடியோ",
          "Infographic": "தகவல் வரைபடம்",
          "Podcast": "பாட்காஸ்ட்",
          "Interactive": "இணைப்பு செயல்பாடு",
          "Share": "பகிரவும்",
          "Learn More": "மேலும் கற்றுக்கொள்ளுங்கள்",
          "My Profile": "என் சுயவிவரம்",
          "Your Impact": "உங்கள் தாக்கம்",
          "Total Donated": "மொத்த நன்கொடை",
          "Donations": "நன்கொடைகள்",
          "Organizations": "அமைப்புகள்",
          "View Detailed Impact": "விவரமான தாக்கத்தை காண்க",
          "Log Out?": "வெளியேற வேண்டுமா?",
          "You will be signed out of the application. Do you really want to log out?":
              "நீங்கள் பயன்பாட்டிலிருந்து வெளியேற்றப்படுவீர்கள். நீங்கள் நிச்சயமாக வெளியேற விரும்புகிறீர்களா?",
          "No": "இல்லை",
          "Yes": "ஆம்",
          "Logout": "வெளியேறவும்",
          "Login/Signup": "உள்நுழைவு/பதிவு",
          "Sign Up/ Login to view details":
              "விவரங்களைப் பார்ப்பதற்கு பதிவு/உள்நுழையவும்",
          "Community Discussion": "சமூக விவாதம்",
          "Create a Post": "ஒரு பதிவை உருவாக்கவும்",
          "Title": "தலைப்பு",
          "Description": "விளக்கம்",
          "Post": "பதிவிடுக",
          "Comments": "கருத்துகள்",
          "Add Comment": "கருத்தைச் சேர்க்கவும்",
          "Comment": "கருத்து",
          "You need to login to comment/post. Please login first.":
              "கருத்து/பதிவிட உள்நுழைய வேண்டும். தயவுசெய்து முதலில் உள்நுழையவும்.",
          "Likes": "விருப்பம்",
          "Profile": "சுயவிவரம்",
          "Awareness": "விழிப்புணர்வு",
          "Volunteer": "தன்னார்வலர்",
          "Dashboard": "டாஷ்போர்டு",
          "Sign Up/ Login to view details": "விவரங்களை பார்க்க பதிவு/உள்நுழையவும்",
          "Community Discussion": "சமூக விவாதம்",
          "Create a Post": "ஒரு பதிவை உருவாக்கவும்",
          "Title": "தலைப்பு",
          "Description": "விளக்கம்",
          "Cancel": "ரத்து செய்யவும்",
          "Post": "பதிவிடுக",
          "Comments": "கருத்துகள்",
          "Likes": "விருப்பம்",
          "Add Comment": "கருத்தைச் சேர்க்கவும்",
          "Comment": "கருத்து",
          "Login Required": "உள்நுழைவு தேவை",
          "You need to login to comment/post. Please login first.": "கருத்து/பதிவிட உள்நுழைய வேண்டும். தயவுசெய்து முதலில் உள்நுழையவும்.",
          "Login": "உள்நுழையவும்",
          "My Profile": "என் சுயவிவரம்",
          "Login/Signup": "உள்நுழைவு/பதிவு",
          "Your Impact": "உங்கள் தாக்கம்",
          "Error loading donations": "நன்கொடைகள் ஏற்றும்போது பிழை",
          "Total Donated": "மொத்த நன்கொடை",
          "Donations": "நன்கொடைகள்",
          "Organizations": "அமைப்புகள்",
          "View Detailed Impact": "விவரமான தாக்கத்தை காண்க",
          "Log Out?": "வெளியேற வேண்டுமா?",
          "You will be signed out of the application. Do you really want to log out?": "நீங்கள் பயன்பாட்டிலிருந்து வெளியேற்றப்படுவீர்கள். நீங்கள் நிச்சயமாக வெளியேற விரும்புகிறீர்களா?",
          "No": "இல்லை",
          "Yes": "ஆம்",
          "Logout": "வெளியேறவும்"
        },
        "kn_IN": {
          "Crisis Dashboard": "ಸಂಕುಲ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
          "Urgent Crises": "ತುರ್ತು ಸಂಕಟಗಳು",
          "Predicted Crises": "ಭವಿಷ್ಯವಾಣಿ ಸಂಕಟಗಳು",
          "Natural Disaster": "ಪ್ರಕೃತಿಪೀಡಿತ ವಿಪತ್ತು",
          "Humanitarian Conflict": "ಮಾನವೀಯ ಸಂಘರ್ಷ",
          "Pandemic": "ಮಹಾಮಾರಿ",
          "Failed to load crisis updates.":
              "ಸಂಕಟ ನವೀಕರಣಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ವಿಫಲವಾಗಿದೆ.",
          "Try Again": "ಮತ್ತೊಮ್ಮೆ ಪ್ರಯತ್ನಿಸಿ",
          "No Title": "ಶೀರ್ಷಿಕೆ ಇಲ್ಲ",
          "No Description Available": "ವಿವರಣೆ ಲಭ್ಯವಿಲ್ಲ",
          "Unknown Location": "ಅಜ್ಞಾತ ಸ್ಥಳ",
          "Unknown": "ಅಜ್ಞಾತ",
          "Volunteering Campaigns": "ಸ್ವಯಂಸೇವಾ ಅಭಿಯಾನಗಳು",
          "You Volunteered in": "ನೀವು ಸ್ವಯಂಸೇವಕರಾಗಿದ್ದೀರಿ",
          "View": "ನೋಡಿರಿ",
          "Featured Campaigns": "ಪ್ರಮುಖ ಅಭಿಯಾನಗಳು",
          "Donate": "ದಾನ ಮಾಡಿ",
          "Make a Difference": "ಬದಲಾವಣೆ ತರಿರಿ",
          "Your support can save lives and provide essential aid.":
              "ನಿಮ್ಮ ಬೆಂಬಲವು ಜೀವಗಳನ್ನು ಉಳಿಸಬಹುದು ಮತ್ತು ಅಗತ್ಯ ಸಹಾಯವನ್ನು ಒದಗಿಸಬಹುದು.",
          "All Causes": "ಎಲ್ಲಾ ಕಾರಣಗಳು",
          "All": "ಎಲ್ಲಾ",
          "Disaster Relief": "ವಿಪತ್ತು ಪರಿಹಾರ",
          "Medical Aid": "ವೈದ್ಯಕೀಯ ಸಹಾಯ",
          "Food & Water": "ಆಹಾರ ಮತ್ತು ನೀರು",
          "Cause 1": "ಕಾರಣ 1",
          "Organization name": "ಸಂಸ್ಥೆಯ ಹೆಸರು",
          "Login Required": "ಲಾಗಿನ್ ಅಗತ್ಯವಿದೆ",
          "You need to login to donate. Please login first.":
              "ದಾನ ಮಾಡಲು ನೀವು ಲಾಗಿನ್ ಮಾಡಬೇಕು. ದಯವಿಟ್ಟು ಮೊದಲು ಲಾಗಿನ್ ಮಾಡಿ.",
          "Cancel": "ರದ್ದು ಮಾಡಿ",
          "Login": "ಲಾಗಿನ್",
          "Learn & Share": "ಕಲಿಯಿರಿ ಮತ್ತು ಹಂಚಿಕೊಳ್ಳಿ",
          "Education & Awareness": "ಶಿಕ್ಷಣ ಮತ್ತು ಜಾಗೃತತೆ",
          "Learn about humanitarian crises and share knowledge":
              "ಮಾನವೀಯ ಸಂಕಟಗಳ ಬಗ್ಗೆ ಕಲಿಯಿರಿ ಮತ್ತು ಜ್ಞಾನ ಹಂಚಿಕೊಳ್ಳಿ",
          "Featured Content": "ಪ್ರಮುಖ ವಿಷಯಗಳು",
          "Educational Resources": "ಶಿಕ್ಷಣ ಸಂಪತ್ತುಗಳು",
          "Active Campaigns": "ಸಕ್ರಿಯ ಅಭಿಯಾನಗಳು",
          "#StandWithRefugees": "#ಕಡತಾರರೊಂದಿಗೆನಿಲ್ಲಿ",
          "Share your support for refugees using the hashtag #StandWithRefugees on social media.":
              "ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮದಲ್ಲಿ #ಕಡತಾರರೊಂದಿಗೆನಿಲ್ಲಿ ಹೆಶ್‌ಟ್ಯಾಗ್ ಬಳಸಿ ಶರಣಾರ್ಥಿಗಳಿಗೆ ನಿಮ್ಮ ಬೆಂಬಲ ಹಂಚಿಕೊಳ್ಳಿ.",
          "#ClimateAction": "#ಹವಾಮಾನಚಟುವಟಿಕೆ",
          "Join the campaign to raise awareness about climate-related disasters.":
              "ಹವಾಮಾನ ಸಂಬಂಧಿತ ವಿಪತ್ತುಗಳ ಬಗ್ಗೆ ಜಾಗೃತಿಯನ್ನು ಹೆಚ್ಚಿಸಲು ಈ ಅಭಿಯಾನದಲ್ಲಿ ಸೇರಿ.",
          "DOCUMENTARY": "ಚಲನಚಿತ್ರ",
          "Understanding Climate Disasters: Causes and Responses":
              "ಹವಾಮಾನ ವಿಪತ್ತುಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳುವುದು: ಕಾರಣಗಳು ಮತ್ತು ಪ್ರತಿಕ್ರಿಯೆಗಳು",
          "Learn how climate change affects disaster frequency and how humanitarian organizations respond.":
              "ಹವಾಮಾನ ಬದಲಾವಣೆ ವಿಪತ್ತುಗಳ ಆವರ್ತನವನ್ನು ಹೇಗೆ ಪ್ರಭಾವಿಸುತ್ತದೆ ಮತ್ತು ಮಾನವೀಯ ಸಂಸ್ಥೆಗಳು ಹೇಗೆ ಪ್ರತಿಕ್ರಿಯಿಸುತ್ತವೆ ಎಂಬುದನ್ನು ಕಲಿಯಿರಿ.",
          "Watch": "ನೋಡಿ",
          "How Humanitarian Aid Works": "ಮಾನವೀಯ ಸಹಾಯ ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
          "Refugee Crisis Explained": "ಶರಣಾರ್ಥಿ ಸಂಕಟ ವಿವರಿಸಲಾಗಿದೆ",
          "Understanding Disaster Response":
              "ವಿಪತ್ತು ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳುವುದು",
          "The Role of NGOs in Crisis Situations":
              "ಸಂಕಟ ಪರಿಸ್ಥಿತಿಗಳಲ್ಲಿ ಎನ್‌ಜಿಒಗಳ ಪಾತ್ರ",
          "Climate Change and Humanitarian Crises":
              "ಹವಾಮಾನ ಬದಲಾವಣೆ ಮತ್ತು ಮಾನವೀಯ ಸಂಕಟಗಳು",
          "Article": "ಲೇಖನ",
          "Video": "ವೀಡಿಯೊ",
          "Infographic": "ಮಾಹಿತಿ ಚಿತ್ರ",
          "Podcast": "ಪಾಡ್ಕಾಸ್ಟ್",
          "Interactive": "ಪರಸ್ಪರ ಕ್ರಿಯಾತ್ಮಕ",
          "Share": "ಹಂಚಿಕೊಳ್ಳಿ",
          "Learn More": "ಹೆಚ್ಚು ತಿಳಿಯಿರಿ",
          "My Profile": "ನನ್ನ ಪ್ರೊಫೈಲ್",
          "Your Impact": "ನಿಮ್ಮ ಪರಿಣಾಮ",
          "Total Donated": "ಒಟ್ಟು ದಾನ",
          "Donations": "ದಾನಗಳು",
          "Organizations": "ಸಂಸ್ಥೆಗಳು",
          "View Detailed Impact": "ವಿವರವಾದ ಪರಿಣಾಮವನ್ನು ನೋಡಿ",
          "Log Out?": "ಲಾಗ್ ಔಟ್ ಮಾಡಬೇಕಾ?",
          "You will be signed out of the application. Do you really want to log out?":
              "ನೀವು ಅಪ್ಲಿಕೇಶನ್‌ನಿಂದ ಲಾಗ್ ಔಟ್ ಆಗಲಿದ್ದೀರಿ. ನೀವು ಖಚಿತವಾಗಿಯೂ ಲಾಗ್ ಔಟ್ ಮಾಡಲು ಬಯಸುವಿರಾ?",
          "No": "ಇಲ್ಲ",
          "Yes": "ಹೌದು",
          "Logout": "ಲಾಗ್ ಔಟ್",
          "Login/Signup": "ಲಾಗಿನ್/ನೋಂದಣಿ",
          "Sign Up/ Login to view details":
              "ವಿವರಗಳನ್ನು ನೋಡಲು ನೋಂದಣಿ/ಲಾಗಿನ್ ಮಾಡಿ",
          "Community Discussion": "ಸಮುದಾಯ ಚರ್ಚೆ",
          "Create a Post": "ಒಂದು ಪೋಸ್ಟ್ ರಚಿಸಿ",
          "Title": "ಶೀರ್ಷಿಕೆ",
          "Description": "ವಿವರಣೆ",
          "Post": "ಪೋಸ್ಟ್",
          "Comments": "ಕಾಮೆಂಟ್‌ಗಳು",
          "Add Comment": "ಕಾಮೆಂಟ್ ಸೇರಿಸಿ",
          "Comment": "ಕಾಮೆಂಟ್",
          "You need to login to comment/post. Please login first.":
              "ಕಾಮೆಂಟ್ ಅಥವಾ ಪೋಸ್ಟ್ ಮಾಡಲು ನೀವು ಲಾಗಿನ್ ಮಾಡಬೇಕು. ದಯವಿಟ್ಟು ಮೊದಲು ಲಾಗಿನ್ ಮಾಡಿ.",
          "Likes": "ಇಷ್ಟಗಳು",
          "Profile": "ಪ್ರೊಫೈಲ್",
          "Awareness": "ಜಾಗೃತತೆ",
          "Volunteer": "ಸ್ವಯಂಸೇವಕ",
          "Dashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
          "Sign Up/ Login to view details": "ವಿವರಗಳನ್ನು ನೋಡಲು ಸೈನ್ ಅಪ್/ಲಾಗಿನ್ ಮಾಡಿ",
          "Community Discussion": "ಸಮುದಾಯ ಚರ್ಚೆ",
          "Create a Post": "ಪೋಸ್ಟ್ ರಚಿಸಿ",
          "Title": "ಶೀರ್ಷಿಕೆ",
          "Description": "ವಿವರಣೆ",
          "Cancel": "ರದ್ದು ಮಾಡಿ",
          "Post": "ಪೋಸ್ಟ್",
          "Comments": "ಕಾಮೆಂಟ್‌ಗಳು",
          "Likes": "ಇಷ್ಟಗಳು",
          "Add Comment": "ಕಾಮೆಂಟ್ ಸೇರಿಸಿ",
          "Comment": "ಕಾಮೆಂಟ್",
          "Login Required": "ಲಾಗಿನ್ ಅಗತ್ಯವಿದೆ",
          "You need to login to comment/post. Please login first.": "ಕಾಮೆಂಟ್ ಅಥವಾ ಪೋಸ್ಟ್ ಮಾಡಲು ನೀವು ಲಾಗಿನ್ ಮಾಡಬೇಕು. ದಯವಿಟ್ಟು ಮೊದಲು ಲಾಗಿನ್ ಮಾಡಿ.",
          "Login": "ಲಾಗಿನ್",
          "My Profile": "ನನ್ನ ಪ್ರೊಫೈಲ್",
          "Login/Signup": "ಲಾಗಿನ್/ನೋಂದಣಿ",
          "Your Impact": "ನಿಮ್ಮ ಪರಿಣಾಮ",
          "Error loading donations": "ದಾನಗಳನ್ನು ಲೋಡ್ ಮಾಡುವಲ್ಲಿ ದೋಷ",
          "Total Donated": "ಒಟ್ಟು ದಾನ",
          "Donations": "ದಾನಗಳು",
          "Organizations": "ಸಂಸ್ಥೆಗಳು",
          "View Detailed Impact": "ವಿವರವಾದ ಪರಿಣಾಮವನ್ನು ನೋಡಿ",
          "Log Out?": "ಲಾಗ್ ಔಟ್ ಮಾಡಬೇಕಾ?",
          "You will be signed out of the application. Do you really want to log out?": "ನೀವು ಅಪ್ಲಿಕೇಶನ್‌ನಿಂದ ಲಾಗ್ ಔಟ್ ಆಗಲಿದ್ದೀರಿ. ನೀವು ಖಚಿತವಾಗಿಯೂ ಲಾಗ್ ಔಟ್ ಮಾಡಲು ಬಯಸುವಿರಾ?",
          "No": "ಇಲ್ಲ",
          "Yes": "ಹೌದು",
          "Logout": "ಲಾಗ್ ಔಟ್"
        },
        "de_DE": {
          "Crisis Dashboard": "Krisen-Dashboard",
          "Urgent Crises": "Dringende Krisen",
          "Predicted Crises": "Vorhergesagte Krisen",
          "Natural Disaster": "Naturkatastrophe",
          "Humanitarian Conflict": "Humanitärer Konflikt",
          "Pandemic": "Pandemie",
          "Failed to load crisis updates.":
              "Fehler beim Laden der Krisen-Updates.",
          "Try Again": "Erneut versuchen",
          "No Title": "Kein Titel",
          "No Description Available": "Keine Beschreibung verfügbar",
          "Unknown Location": "Unbekannter Ort",
          "Unknown": "Unbekannt",
          "Volunteering Campaigns": "Freiwilligenkampagnen",
          "You Volunteered in": "Sie haben sich engagiert in",
          "View": "Ansehen",
          "Featured Campaigns": "Empfohlene Kampagnen",
          "Donate": "Spenden",
          "Make a Difference": "Einen Unterschied machen",
          "Your support can save lives and provide essential aid.":
              "Ihre Unterstützung kann Leben retten und wichtige Hilfe leisten.",
          "All Causes": "Alle Anliegen",
          "All": "Alle",
          "Disaster Relief": "Katastrophenhilfe",
          "Medical Aid": "Medizinische Hilfe",
          "Food & Water": "Essen & Wasser",
          "Cause 1": "Anliegen 1",
          "Organization name": "Organisationsname",
          "Login Required": "Anmeldung erforderlich",
          "You need to login to donate. Please login first.":
              "Sie müssen sich anmelden, um zu spenden. Bitte zuerst anmelden.",
          "Cancel": "Abbrechen",
          "Login": "Anmelden",
          "Learn & Share": "Lernen & Teilen",
          "Education & Awareness": "Bildung & Bewusstsein",
          "Learn about humanitarian crises and share knowledge":
              "Erfahren Sie mehr über humanitäre Krisen und teilen Sie Ihr Wissen",
          "Featured Content": "Empfohlener Inhalt",
          "Educational Resources": "Bildungsressourcen",
          "Active Campaigns": "Aktive Kampagnen",
          "#StandWithRefugees": "#StehtMitFlüchtlingen",
          "Share your support for refugees using the hashtag #StandWithRefugees on social media.":
              "Teilen Sie Ihre Unterstützung für Flüchtlinge mit dem Hashtag #StehtMitFlüchtlingen in sozialen Medien.",
          "#ClimateAction": "#Klimaschutz",
          "Join the campaign to raise awareness about climate-related disasters.":
              "Treten Sie der Kampagne bei, um das Bewusstsein für klimabezogene Katastrophen zu schärfen.",
          "DOCUMENTARY": "DOKUMENTATION",
          "Understanding Climate Disasters: Causes and Responses":
              "Verständnis für Klimakatastrophen: Ursachen und Reaktionen",
          "Learn how climate change affects disaster frequency and how humanitarian organizations respond.":
              "Erfahren Sie, wie der Klimawandel die Häufigkeit von Katastrophen beeinflusst und wie humanitäre Organisationen darauf reagieren.",
          "Watch": "Ansehen",
          "How Humanitarian Aid Works": "Wie humanitäre Hilfe funktioniert",
          "Refugee Crisis Explained": "Die Flüchtlingskrise erklärt",
          "Understanding Disaster Response": "Katastrophenreaktion verstehen",
          "The Role of NGOs in Crisis Situations":
              "Die Rolle von NGOs in Krisensituationen",
          "Climate Change and Humanitarian Crises":
              "Klimawandel und humanitäre Krisen",
          "Article": "Artikel",
          "Video": "Video",
          "Infographic": "Infografik",
          "Podcast": "Podcast",
          "Interactive": "Interaktiv",
          "Share": "Teilen",
          "Learn More": "Mehr erfahren",
          "My Profile": "Mein Profil",
          "Your Impact": "Ihr Einfluss",
          "Total Donated": "Gesamt gespendet",
          "Donations": "Spenden",
          "Organizations": "Organisationen",
          "View Detailed Impact": "Detaillierte Auswirkungen ansehen",
          "Log Out?": "Abmelden?",
          "You will be signed out of the application. Do you really want to log out?":
              "Sie werden von der Anwendung abgemeldet. Möchten Sie sich wirklich abmelden?",
          "No": "Nein",
          "Yes": "Ja",
          "Logout": "Abmelden",
          "Login/Signup": "Anmelden/Registrieren",
          "Sign Up/ Login to view details":
              "Registrieren/Anmelden, um Details zu sehen",
          "Community Discussion": "Community-Diskussion",
          "Create a Post": "Einen Beitrag erstellen",
          "Title": "Titel",
          "Description": "Beschreibung",
          "Post": "Beitrag",
          "Comments": "Kommentare",
          "Add Comment": "Kommentar hinzufügen",
          "Comment": "Kommentar",
          "You need to login to comment/post. Please login first.":
              "Sie müssen sich anmelden, um zu kommentieren oder zu posten. Bitte zuerst anmelden.",
          "Likes": "Gefällt mir",
          "Profile": "Profil",
          "Awareness": "Bewusstsein",
          "Volunteer": "Freiwilliger",
          "Dashboard": "Dashboard",
          "Sign Up/ Login to view details": "Registrieren/Anmelden, um Details zu sehen",
          "Community Discussion": "Community-Diskussion",
          "Create a Post": "Einen Beitrag erstellen",
          "Title": "Titel",
          "Description": "Beschreibung",
          "Cancel": "Abbrechen",
          "Post": "Beitrag",
          "Comments": "Kommentare",
          "Likes": "Gefällt mir",
          "Add Comment": "Kommentar hinzufügen",
          "Comment": "Kommentar",
          "Login Required": "Anmeldung erforderlich",
          "You need to login to comment/post. Please login first.": "Sie müssen sich anmelden, um zu kommentieren oder zu posten. Bitte zuerst anmelden.",
          "Login": "Anmelden",
          "My Profile": "Mein Profil",
          "Login/Signup": "Anmelden/Registrieren",
          "Your Impact": "Ihr Einfluss",
          "Error loading donations": "Fehler beim Laden der Spenden",
          "Total Donated": "Gesamt gespendet",
          "Donations": "Spenden",
          "Organizations": "Organisationen",
          "View Detailed Impact": "Detaillierte Auswirkungen ansehen",
          "Log Out?": "Abmelden?",
          "You will be signed out of the application. Do you really want to log out?": "Sie werden von der Anwendung abgemeldet. Möchten Sie sich wirklich abmelden?",
          "No": "Nein",
          "Yes": "Ja",
          "Logout": "Abmelden"
        },
        "fr_FR": {
          "Crisis Dashboard": "Tableau de bord des crises",
          "Urgent Crises": "Crises urgentes",
          "Predicted Crises": "Crises prévues",
          "Natural Disaster": "Catastrophe naturelle",
          "Humanitarian Conflict": "Conflit humanitaire",
          "Pandemic": "Pandémie",
          "Failed to load crisis updates.":
              "Échec du chargement des mises à jour de crise.",
          "Try Again": "Réessayer",
          "No Title": "Aucun titre",
          "No Description Available": "Aucune description disponible",
          "Unknown Location": "Lieu inconnu",
          "Unknown": "Inconnu",
          "Volunteering Campaigns": "Campagnes de bénévolat",
          "You Volunteered in": "Vous avez fait du bénévolat dans",
          "View": "Voir",
          "Featured Campaigns": "Campagnes en vedette",
          "Donate": "Faire un don",
          "Make a Difference": "Faire une différence",
          "Your support can save lives and provide essential aid.":
              "Votre soutien peut sauver des vies et fournir une aide essentielle.",
          "All Causes": "Toutes les causes",
          "All": "Tous",
          "Disaster Relief": "Aide aux catastrophes",
          "Medical Aid": "Aide médicale",
          "Food & Water": "Nourriture et eau",
          "Cause 1": "Cause 1",
          "Organization name": "Nom de l'organisation",
          "Login Required": "Connexion requise",
          "You need to login to donate. Please login first.":
              "Vous devez vous connecter pour faire un don. Veuillez vous connecter d'abord.",
          "Cancel": "Annuler",
          "Login": "Se connecter",
          "Learn & Share": "Apprendre & Partager",
          "Education & Awareness": "Éducation et sensibilisation",
          "Learn about humanitarian crises and share knowledge":
              "Apprenez-en plus sur les crises humanitaires et partagez vos connaissances",
          "Featured Content": "Contenu en vedette",
          "Educational Resources": "Ressources éducatives",
          "Active Campaigns": "Campagnes actives",
          "#StandWithRefugees": "#SoutienAuxRéfugiés",
          "Share your support for refugees using the hashtag #StandWithRefugees on social media.":
              "Montrez votre soutien aux réfugiés en utilisant le hashtag #SoutienAuxRéfugiés sur les réseaux sociaux.",
          "#ClimateAction": "#ActionClimatique",
          "Join the campaign to raise awareness about climate-related disasters.":
              "Rejoignez la campagne pour sensibiliser aux catastrophes climatiques.",
          "DOCUMENTARY": "DOCUMENTAIRE",
          "Understanding Climate Disasters: Causes and Responses":
              "Comprendre les catastrophes climatiques : causes et réponses",
          "Learn how climate change affects disaster frequency and how humanitarian organizations respond.":
              "Découvrez comment le changement climatique affecte la fréquence des catastrophes et comment les organisations humanitaires réagissent.",
          "Watch": "Regarder",
          "How Humanitarian Aid Works": "Comment fonctionne l'aide humanitaire",
          "Refugee Crisis Explained": "Explication de la crise des réfugiés",
          "Understanding Disaster Response":
              "Comprendre la réponse aux catastrophes",
          "The Role of NGOs in Crisis Situations":
              "Le rôle des ONG dans les situations de crise",
          "Climate Change and Humanitarian Crises":
              "Changement climatique et crises humanitaires",
          "Article": "Article",
          "Video": "Vidéo",
          "Infographic": "Infographie",
          "Podcast": "Podcast",
          "Interactive": "Interactif",
          "Share": "Partager",
          "Learn More": "En savoir plus",
          "My Profile": "Mon profil",
          "Your Impact": "Votre impact",
          "Total Donated": "Total des dons",
          "Donations": "Dons",
          "Organizations": "Organisations",
          "View Detailed Impact": "Voir l'impact détaillé",
          "Log Out?": "Se déconnecter ?",
          "You will be signed out of the application. Do you really want to log out?":
              "Vous serez déconnecté de l'application. Voulez-vous vraiment vous déconnecter ?",
          "No": "Non",
          "Yes": "Oui",
          "Logout": "Se déconnecter",
          "Login/Signup": "Connexion/Inscription",
          "Sign Up/ Login to view details":
              "Inscrivez-vous / Connectez-vous pour voir les détails",
          "Community Discussion": "Discussion communautaire",
          "Create a Post": "Créer un post",
          "Title": "Titre",
          "Description": "Description",
          "Post": "Publier",
          "Comments": "Commentaires",
          "Add Comment": "Ajouter un commentaire",
          "Comment": "Commentaire",
          "You need to login to comment/post. Please login first.":
              "Vous devez vous connecter pour commenter ou publier. Veuillez vous connecter d'abord.",
          "Likes": "J'aime",
          "Profile": "Profil",
          "Awareness": "Sensibilisation",
          "Volunteer": "Bénévole",
          "Dashboard": "Tableau de bord",
          "Sign Up/ Login to view details": "Inscrivez-vous / Connectez-vous pour voir les détails",
          "Community Discussion": "Discussion communautaire",
          "Create a Post": "Créer un post",
          "Title": "Titre",
          "Description": "Description",
          "Cancel": "Annuler",
          "Post": "Publier",
          "Comments": "Commentaires",
          "Likes": "J'aime",
          "Add Comment": "Ajouter un commentaire",
          "Comment": "Commentaire",
          "Login Required": "Connexion requise",
          "You need to login to comment/post. Please login first.": "Vous devez vous connecter pour commenter ou publier. Veuillez vous connecter d'abord.",
          "Login": "Se connecter",
          "My Profile": "Mon profil",
          "Login/Signup": "Connexion/Inscription",
          "Your Impact": "Votre impact",
          "Error loading donations": "Erreur de chargement des dons",
          "Total Donated": "Total des dons",
          "Donations": "Dons",
          "Organizations": "Organisations",
          "View Detailed Impact": "Voir l'impact détaillé",
          "Log Out?": "Se déconnecter ?",
          "You will be signed out of the application. Do you really want to log out?": "Vous serez déconnecté de l'application. Voulez-vous vraiment vous déconnecter ?",
          "No": "Non",
          "Yes": "Oui",
          "Logout": "Se déconnecter"
        },
        "ja_JP": {
          "Crisis Dashboard": "危機ダッシュボード",
          "Urgent Crises": "緊急の危機",
          "Predicted Crises": "予測された危機",
          "Natural Disaster": "自然災害",
          "Humanitarian Conflict": "人道的紛争",
          "Pandemic": "パンデミック",
          "Failed to load crisis updates.": "危機の更新を読み込めませんでした。",
          "Try Again": "再試行",
          "No Title": "タイトルなし",
          "No Description Available": "説明なし",
          "Unknown Location": "不明な場所",
          "Unknown": "不明",
          "Volunteering Campaigns": "ボランティア活動",
          "You Volunteered in": "参加したボランティア",
          "View": "表示",
          "Featured Campaigns": "注目のキャンペーン",
          "Donate": "寄付する",
          "Make a Difference": "違いを生み出す",
          "Your support can save lives and provide essential aid.":
              "あなたの支援は命を救い、必要な支援を提供できます。",
          "All Causes": "すべての支援対象",
          "All": "すべて",
          "Disaster Relief": "災害支援",
          "Medical Aid": "医療支援",
          "Food & Water": "食料と水",
          "Cause 1": "支援対象 1",
          "Organization name": "団体名",
          "Login Required": "ログインが必要です",
          "You need to login to donate. Please login first.":
              "寄付するにはログインが必要です。先にログインしてください。",
          "Cancel": "キャンセル",
          "Login": "ログイン",
          "Learn & Share": "学びと共有",
          "Education & Awareness": "教育と意識向上",
          "Learn about humanitarian crises and share knowledge":
              "人道的危機について学び、知識を共有しましょう",
          "Featured Content": "注目のコンテンツ",
          "Educational Resources": "教育資料",
          "Active Campaigns": "活動中のキャンペーン",
          "#StandWithRefugees": "#難民と共に",
          "Share your support for refugees using the hashtag #StandWithRefugees on social media.":
              "ハッシュタグ #難民と共に を使って難民支援を広めましょう。",
          "#ClimateAction": "#気候変動対策",
          "Join the campaign to raise awareness about climate-related disasters.":
              "気候変動に関する災害についての認識を高めるキャンペーンに参加しましょう。",
          "DOCUMENTARY": "ドキュメンタリー",
          "Understanding Climate Disasters: Causes and Responses":
              "気候災害の理解：原因と対応",
          "Learn how climate change affects disaster frequency and how humanitarian organizations respond.":
              "気候変動が災害の発生頻度にどのように影響し、人道的組織がどのように対応するかを学びましょう。",
          "Watch": "見る",
          "How Humanitarian Aid Works": "人道支援の仕組み",
          "Refugee Crisis Explained": "難民危機の解説",
          "Understanding Disaster Response": "災害対応の理解",
          "The Role of NGOs in Crisis Situations": "危機におけるNGOの役割",
          "Climate Change and Humanitarian Crises": "気候変動と人道的危機",
          "Article": "記事",
          "Video": "動画",
          "Infographic": "インフォグラフィック",
          "Podcast": "ポッドキャスト",
          "Interactive": "インタラクティブ",
          "Share": "共有",
          "Learn More": "詳しく学ぶ",
          "My Profile": "マイプロフィール",
          "Your Impact": "あなたの影響",
          "Total Donated": "寄付総額",
          "Donations": "寄付",
          "Organizations": "団体",
          "View Detailed Impact": "詳細な影響を表示",
          "Log Out?": "ログアウトしますか？",
          "You will be signed out of the application. Do you really want to log out?":
              "アプリケーションからログアウトされます。本当にログアウトしますか？",
          "No": "いいえ",
          "Yes": "はい",
          "Logout": "ログアウト",
          "Login/Signup": "ログイン/登録",
          "Sign Up/ Login to view details": "詳細を見るには登録/ログインしてください",
          "Community Discussion": "コミュニティディスカッション",
          "Create a Post": "投稿を作成",
          "Title": "タイトル",
          "Description": "説明",
          "Post": "投稿",
          "Comments": "コメント",
          "Add Comment": "コメントを追加",
          "Comment": "コメント",
          "You need to login to comment/post. Please login first.":
              "コメントや投稿をするにはログインが必要です。先にログインしてください。",
          "Likes": "いいね",
          "Profile": "プロフィール",
          "Awareness": "意識向上",
          "Volunteer": "ボランティア",
          "Dashboard": "ダッシュボード",
          "Sign Up/ Login to view details": "詳細を見るには登録/ログインしてください",
          "Community Discussion": "コミュニティディスカッション",
          "Create a Post": "投稿を作成",
          "Title": "タイトル",
          "Description": "説明",
          "Cancel": "キャンセル",
          "Post": "投稿",
          "Comments": "コメント",
          "Likes": "いいね",
          "Add Comment": "コメントを追加",
          "Comment": "コメント",
          "Login Required": "ログインが必要です",
          "You need to login to comment/post. Please login first.": "コメントや投稿をするにはログインが必要です。先にログインしてください。",
          "Login": "ログイン",
          "My Profile": "マイプロフィール",
          "Login/Signup": "ログイン/登録",
          "Your Impact": "あなたの影響",
          "Error loading donations": "寄付の読み込みエラー",
          "Total Donated": "寄付総額",
          "Donations": "寄付",
          "Organizations": "団体",
          "View Detailed Impact": "詳細な影響を表示",
          "Log Out?": "ログアウトしますか？",
          "You will be signed out of the application. Do you really want to log out?": "アプリケーションからログアウトされます。本当にログアウトしますか？",
          "No": "いいえ",
          "Yes": "はい",
          "Logout": "ログアウト"
        },
        "zh_CN": {
          "Crisis Dashboard": "危机仪表板",
          "Urgent Crises": "紧急危机",
          "Predicted Crises": "预测危机",
          "Natural Disaster": "自然灾害",
          "Humanitarian Conflict": "人道冲突",
          "Pandemic": "大流行",
          "Failed to load crisis updates.": "无法加载危机更新。",
          "Try Again": "重试",
          "No Title": "无标题",
          "No Description Available": "无可用描述",
          "Unknown Location": "未知地点",
          "Unknown": "未知",
          "Volunteering Campaigns": "志愿活动",
          "You Volunteered in": "您参与的志愿活动",
          "View": "查看",
          "Featured Campaigns": "精选活动",
          "Donate": "捐赠",
          "Make a Difference": "做出改变",
          "Your support can save lives and provide essential aid.":
              "您的支持可以挽救生命并提供必要的援助。",
          "All Causes": "所有援助",
          "All": "全部",
          "Disaster Relief": "灾难救助",
          "Medical Aid": "医疗援助",
          "Food & Water": "食物和水",
          "Cause 1": "援助目标 1",
          "Organization name": "组织名称",
          "Login Required": "需要登录",
          "You need to login to donate. Please login first.": "您需要登录才能捐赠。请先登录。",
          "Cancel": "取消",
          "Login": "登录",
          "Learn & Share": "学习与分享",
          "Education & Awareness": "教育与意识",
          "Learn about humanitarian crises and share knowledge": "了解人道危机并分享知识",
          "Featured Content": "精选内容",
          "Educational Resources": "教育资源",
          "Active Campaigns": "活跃活动",
          "#StandWithRefugees": "#与难民同在",
          "Share your support for refugees using the hashtag #StandWithRefugees on social media.":
              "在社交媒体上使用 #与难民同在 话题分享您的支持。",
          "#ClimateAction": "#气候行动",
          "Join the campaign to raise awareness about climate-related disasters.":
              "加入活动，提高对气候相关灾害的认识。",
          "DOCUMENTARY": "纪录片",
          "Understanding Climate Disasters: Causes and Responses":
              "理解气候灾害：原因与应对",
          "Learn how climate change affects disaster frequency and how humanitarian organizations respond.":
              "了解气候变化如何影响灾害频率，以及人道组织如何应对。",
          "Watch": "观看",
          "How Humanitarian Aid Works": "人道援助的运作方式",
          "Refugee Crisis Explained": "难民危机解析",
          "Understanding Disaster Response": "了解灾难应对",
          "The Role of NGOs in Crisis Situations": "危机情况下 NGO 的作用",
          "Climate Change and Humanitarian Crises": "气候变化与人道危机",
          "Article": "文章",
          "Video": "视频",
          "Infographic": "信息图",
          "Podcast": "播客",
          "Interactive": "互动",
          "Share": "分享",
          "Learn More": "了解更多",
          "My Profile": "我的资料",
          "Your Impact": "您的影响",
          "Total Donated": "总捐款",
          "Donations": "捐赠",
          "Organizations": "组织",
          "View Detailed Impact": "查看详细影响",
          "Log Out?": "退出登录？",
          "You will be signed out of the application. Do you really want to log out?":
              "您将退出应用程序。您确定要退出吗？",
          "No": "否",
          "Yes": "是",
          "Logout": "退出",
          "Login/Signup": "登录/注册",
          "Sign Up/ Login to view details": "注册/登录以查看详细信息",
          "Community Discussion": "社区讨论",
          "Create a Post": "创建帖子",
          "Title": "标题",
          "Description": "描述",
          "Post": "发布",
          "Comments": "评论",
          "Add Comment": "添加评论",
          "Comment": "评论",
          "You need to login to comment/post. Please login first.":
              "您需要登录才能评论/发布。请先登录。",
          "Likes": "点赞",
          "Profile": "个人资料",
          "Awareness": "意识提升",
          "Volunteer": "志愿者",
          "Dashboard": "仪表板",
          "Sign Up/ Login to view details": "注册/登录以查看详细信息",
          "Community Discussion": "社区讨论",
          "Create a Post": "创建帖子",
          "Title": "标题",
          "Description": "描述",
          "Cancel": "取消",
          "Post": "发布",
          "Comments": "评论",
          "Likes": "点赞",
          "Add Comment": "添加评论",
          "Comment": "评论",
          "Login Required": "需要登录",
          "You need to login to comment/post. Please login first.": "您需要登录才能评论/发布。请先登录。",
          "Login": "登录",
          "My Profile": "我的资料",
          "Login/Signup": "登录/注册",
          "Your Impact": "您的影响",
          "Error loading donations": "加载捐款时出错",
          "Total Donated": "总捐款",
          "Donations": "捐赠",
          "Organizations": "组织",
          "View Detailed Impact": "查看详细影响",
          "Log Out?": "退出登录？",
          "You will be signed out of the application. Do you really want to log out?": "您将退出应用程序。您确定要退出吗？",
          "No": "否",
          "Yes": "是",
          "Logout": "退出"
        },
        "ko_KR": {
          "Crisis Dashboard": "위기 대시보드",
          "Urgent Crises": "긴급 위기",
          "Predicted Crises": "예측된 위기",
          "Natural Disaster": "자연 재해",
          "Humanitarian Conflict": "인도적 분쟁",
          "Pandemic": "전염병",
          "Failed to load crisis updates.": "위기 업데이트를 불러오는 데 실패했습니다.",
          "Try Again": "다시 시도",
          "No Title": "제목 없음",
          "No Description Available": "설명 없음",
          "Unknown Location": "알 수 없는 위치",
          "Unknown": "알 수 없음",
          "Volunteering Campaigns": "자원봉사 캠페인",
          "You Volunteered in": "참여한 자원봉사",
          "View": "보기",
          "Featured Campaigns": "추천 캠페인",
          "Donate": "기부하기",
          "Make a Difference": "변화를 만들어 보세요",
          "Your support can save lives and provide essential aid.":
              "당신의 지원은 생명을 구하고 필수적인 지원을 제공할 수 있습니다.",
          "All Causes": "모든 원인",
          "All": "전체",
          "Disaster Relief": "재난 구호",
          "Medical Aid": "의료 지원",
          "Food & Water": "식량 및 식수",
          "Cause 1": "원인 1",
          "Organization name": "기관 이름",
          "Login Required": "로그인 필요",
          "You need to login to donate. Please login first.":
              "기부하려면 로그인해야 합니다. 먼저 로그인하세요.",
          "Cancel": "취소",
          "Login": "로그인",
          "Learn & Share": "배우고 공유하기",
          "Education & Awareness": "교육 및 인식",
          "Learn about humanitarian crises and share knowledge":
              "인도적 위기에 대해 배우고 지식을 공유하세요.",
          "Featured Content": "추천 콘텐츠",
          "Educational Resources": "교육 자료",
          "Active Campaigns": "진행 중인 캠페인",
          "#StandWithRefugees": "#난민과함께",
          "Share your support for refugees using the hashtag #StandWithRefugees on social media.":
              "소셜 미디어에서 #난민과함께 해시태그를 사용하여 난민을 지지하세요.",
          "#ClimateAction": "#기후행동",
          "Join the campaign to raise awareness about climate-related disasters.":
              "기후 관련 재난에 대한 인식을 높이기 위한 캠페인에 참여하세요.",
          "DOCUMENTARY": "다큐멘터리",
          "Understanding Climate Disasters: Causes and Responses":
              "기후 재난 이해하기: 원인과 대응",
          "Learn how climate change affects disaster frequency and how humanitarian organizations respond.":
              "기후 변화가 재난 빈도에 미치는 영향과 인도적 단체의 대응 방안을 알아보세요.",
          "Watch": "시청",
          "How Humanitarian Aid Works": "인도적 지원의 작동 방식",
          "Refugee Crisis Explained": "난민 위기 설명",
          "Understanding Disaster Response": "재난 대응 이해하기",
          "The Role of NGOs in Crisis Situations": "위기 상황에서 NGO의 역할",
          "Climate Change and Humanitarian Crises": "기후 변화와 인도적 위기",
          "Article": "기사",
          "Video": "비디오",
          "Infographic": "인포그래픽",
          "Podcast": "팟캐스트",
          "Interactive": "인터랙티브",
          "Share": "공유",
          "Learn More": "더 알아보기",
          "My Profile": "내 프로필",
          "Your Impact": "나의 영향",
          "Total Donated": "총 기부 금액",
          "Donations": "기부",
          "Organizations": "기관",
          "View Detailed Impact": "자세한 영향 보기",
          "Log Out?": "로그아웃하시겠습니까?",
          "You will be signed out of the application. Do you really want to log out?":
              "앱에서 로그아웃됩니다. 정말 로그아웃하시겠습니까?",
          "No": "아니요",
          "Yes": "예",
          "Logout": "로그아웃",
          "Login/Signup": "로그인/회원가입",
          "Sign Up/ Login to view details": "세부 정보를 보려면 가입/로그인하세요.",
          "Community Discussion": "커뮤니티 토론",
          "Create a Post": "게시물 작성",
          "Title": "제목",
          "Description": "설명",
          "Post": "게시",
          "Comments": "댓글",
          "Add Comment": "댓글 추가",
          "Comment": "댓글",
          "You need to login to comment/post. Please login first.":
              "댓글을 달거나 게시하려면 로그인해야 합니다. 먼저 로그인하세요.",
          "Likes": "좋아요",
          "Profile": "프로필",
          "Awareness": "인식",
          "Volunteer": "자원봉사",
          "Dashboard": "대시보드",
          "Sign Up/ Login to view details": "세부 정보를 보려면 가입/로그인하세요.",
          "Community Discussion": "커뮤니티 토론",
          "Create a Post": "게시물 작성",
          "Title": "제목",
          "Description": "설명",
          "Cancel": "취소",
          "Post": "게시",
          "Comments": "댓글",
          "Likes": "좋아요",
          "Add Comment": "댓글 추가",
          "Comment": "댓글",
          "Login Required": "로그인 필요",
          "You need to login to comment/post. Please login first.": "댓글을 달거나 게시하려면 로그인해야 합니다. 먼저 로그인하세요.",
          "Login": "로그인",
          "My Profile": "내 프로필",
          "Login/Signup": "로그인/회원가입",
          "Your Impact": "나의 영향",
          "Error loading donations": "기부 내역을 불러오는 중 오류 발생",
          "Total Donated": "총 기부 금액",
          "Donations": "기부",
          "Organizations": "기관",
          "View Detailed Impact": "자세한 영향 보기",
          "Log Out?": "로그아웃하시겠습니까?",
          "You will be signed out of the application. Do you really want to log out?": "앱에서 로그아웃됩니다. 정말 로그아웃하시겠습니까?",
          "No": "아니요",
          "Yes": "예",
          "Logout": "로그아웃"
        },
      };
}
